[package]
name = "stacks-signer"
version = "0.0.1"
authors = [ "Jude Nelson <jude@stacks.org>" ]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Stacker signer binary"
keywords = [ "stacks", "stx", "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"
resolver = "2"
edition = "2021"

[lib]
name = "stacks_signer"
path = "src/lib.rs"

[[bin]]
name = "stacks-signer"
path = "src/main.rs"

[dependencies]
backoff = { workspace = true }
clarity = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
hashbrown = { workspace = true }
lazy_static = { workspace = true }
libsigner = { workspace = true }
libstackerdb = { workspace = true }
prometheus = { workspace = true, optional = true }
rand_core = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "json", "rustls-tls"] }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_stacker = { workspace = true }
slog = { workspace = true, features = ["max_level_trace"] }
slog-json = { workspace = true, optional = true }
slog-term = { workspace = true }
stacks-common = { workspace = true }
stackslib = { workspace = true }
thiserror = { workspace = true }
tiny_http = { workspace = true, optional = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
rand = { workspace = true }
url = { workspace = true }
rusqlite = { workspace = true, features = ["functions"] }
serde_json= { workspace = true, features = ["arbitrary_precision", "unbounded_depth"] }
secp256k1= { workspace = true, features = ["serde", "recovery"] }

[dev-dependencies]
clarity = { workspace = true, features = ["testing"] }
stacks-common = { workspace = true, features = ["testing"] }
num-traits = { workspace = true }

[features]
monitoring_prom = ["libsigner/monitoring_prom", "prometheus", "tiny_http"]
testing = []
