[package]
name = "stackslib"
version = "0.0.1"
authors = [ "Jude Nelson <jude@stacks.org>",
            "Aaron Blankstein <aaron@blockstack.com>",
            "Ludo Galabru <ludovic@blockstack.com>" ]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Reference implementation of the Stacks 2.0 Blockchain"
keywords = [ "stacks", "stx", "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"
resolver = "2"
edition = "2021"
rust-version = "1.80"

[lib]
name = "blockstack_lib"
path = "src/lib.rs"

[[bin]]
name = "stacks-inspect"
path = "src/main.rs"

[[bin]]
name = "clarity-cli"
path = "src/clarity_cli_main.rs"

[[bin]]
name = "blockstack-cli"
path = "src/blockstack_cli.rs"

[dependencies]
rand = { workspace = true }
rand_core = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_stacker = { workspace = true }
sha3 = { workspace = true }
ripemd = { workspace = true }
regex = { workspace = true }
mio = { workspace = true }
lazy_static = { workspace = true }
url = { workspace = true }
percent-encoding = { workspace = true }
prometheus = { workspace = true, optional = true }
integer-sqrt = { workspace = true }
slog = { workspace = true, features = ["max_level_trace"] }
slog-term = { workspace = true }
slog-json = { workspace = true, optional = true }
chrono = { workspace = true }
libc = { workspace = true }
clarity = { workspace = true }
stacks-common = { workspace = true }
pox-locking = { workspace = true }
libstackerdb = { workspace = true }
siphasher = { workspace = true }
hashbrown = { workspace = true }
rusqlite = { workspace = true }
toml = { workspace = true }
serde_json= { workspace = true, features = ["arbitrary_precision", "unbounded_depth"] }
secp256k1= { workspace = true, features = ["serde", "recovery"] }
curve25519-dalek= { workspace = true, features = ["serde"] }
time= { workspace = true, features = ["std"] }

[target.'cfg(not(any(target_os = "macos",target_os="windows", target_arch = "arm" )))'.dependencies]
tikv-jemallocator = {workspace = true}

[target.'cfg(unix)'.dependencies]
nix = "0.23"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "handleapi", "synchapi", "winbase"] }

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["fileapi", "processenv", "winnt"] }

[dependencies.ed25519-dalek]
workspace = true

[dev-dependencies]
assert-json-diff = { workspace = true }
stdext = { workspace = true }
stx-genesis = { workspace = true }
clarity = { workspace = true, features = ["default", "testing"] }
stacks-common = { workspace = true, features = ["default", "testing"] }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
mutants = { workspace = true }
rlimit = { workspace = true }

[features]
default = []
profile-sqlite = []
disable-costs = []
developer-mode = ["clarity/developer-mode"]
monitoring_prom = ["prometheus"]
slog_json = ["slog-json", "stacks-common/slog_json", "clarity/slog_json", "pox-locking/slog_json"]
testing = []

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64"), not(any(target_os="windows"))))'.dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(any(not(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")), any(target_os="windows")))'.dependencies]
sha2 = { version = "0.10" }
