[package]
name = "stacks-common"
version = "0.0.1"
authors = [ "Jude Nelson <jude@stacks.org>",
            "Aaron Blankstein <aaron@blockstack.com>",
            "Ludo Galabru <ludovic@blockstack.com>" ]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Common modules for blockstack_lib, libclarity"
keywords = [ "stacks", "stx", "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"
resolver = "2"
edition = "2021"
build = "build.rs"

[lib]
name = "stacks_common"
path = "./src/libcommon.rs"

[dependencies]
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_derive = { workspace = true }
sha3 = { workspace = true }
ripemd = { workspace = true }
lazy_static = { workspace = true }
slog = { workspace = true, features = ["max_level_trace"] }
slog-term = { workspace = true }
slog-json = { workspace = true, optional = true }
chrono = { workspace = true }
libc = { workspace = true }
hashbrown = { workspace = true }
rusqlite = { workspace = true, optional = true }
serde_json= { workspace = true, features = ["arbitrary_precision", "unbounded_depth"] }
secp256k1= { workspace = true, features = ["serde", "recovery"] }
curve25519-dalek= { workspace = true, features = ["serde"] }
time= { workspace = true, features = ["std"] }

[target.'cfg(unix)'.dependencies]
nix = "0.23"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "handleapi", "synchapi", "winbase"] }

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["fileapi", "processenv", "winnt"] }

[dependencies.ed25519-dalek]
workspace = true

[dev-dependencies]
rand_core = { workspace = true }

[features]
default = ["canonical", "developer-mode"]
canonical = ["rusqlite"]
developer-mode = []
slog_json = ["slog-json"]
testing = ["canonical"]
serde = []
bech32_std = []
bech32_strict = []

[build-dependencies]
toml = { workspace = true }

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64"), not(any(target_os="windows"))))'.dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(any(not(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")), any(target_os="windows")))'.dependencies]
sha2 = { version = "0.10" }
