[package]
name = "libsigner"
version = "0.0.1"
authors = [ "Jude Nelson <jude@stacks.org>" ]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Library for Stacks signer daemons"
keywords = [ "stacks", "stx", "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"
resolver = "2"
edition = "2021"

[lib]
name = "libsigner"
path = "./src/libsigner.rs"

[dependencies]
clarity = { workspace = true }
hashbrown = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
libstackerdb = { workspace = true }
prometheus = { workspace = true, optional = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_stacker = { workspace = true }
slog = { workspace = true, features = ["max_level_trace"] }
slog-term = { workspace = true }
slog-json = { workspace = true, optional = true }
stacks-common = { workspace = true }
stackslib = { workspace = true }
thiserror = { workspace = true }
tiny_http = { workspace = true }
serde_json= { workspace = true, features = ["arbitrary_precision", "unbounded_depth"] }
secp256k1= { workspace = true, features = ["serde", "recovery"] }

[dev-dependencies]
mutants = { workspace = true }
rand_core = { workspace = true }
rand = { workspace = true }

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64"), not(any(target_os="windows"))))'.dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(any(not(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")), any(target_os = "windows")))'.dependencies]
sha2 = { version = "0.10" }

[features]
monitoring_prom = ["prometheus"]
