[package]
name = "clarity"
version = "0.0.1"
authors = [ "Jude Nelson <jude@stacks.org>",
            "Aaron Blankstein <aaron@blockstack.com>",
            "Ludo Galabru <ludovic@blockstack.com>" ]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Reference implementation of the Stacks 2.0 Blockchain"
keywords = [ "stacks", "stx", "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"
edition = "2021"
resolver = "2"

[lib]
name = "clarity"
path = "./src/libclarity.rs"

[dependencies]
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_stacker = { workspace = true }
regex = { workspace = true }
lazy_static = { workspace = true }
integer-sqrt = { workspace = true }
slog = { workspace = true, features = ["max_level_trace"] }
stacks-common = { workspace = true, optional = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
hashbrown = { workspace = true }
rusqlite = { workspace = true, optional = true}
serde_json= { workspace = true, features = ["arbitrary_precision", "unbounded_depth"] }
time= { workspace = true, features = ["std"] }

[dev-dependencies]
assert-json-diff = { workspace = true }
mutants = { workspace = true }
# a nightly rustc regression (35dbef235 2021-03-02) prevents criterion from compiling
#  but it isn't necessary for tests: only benchmarks. therefore, commenting out for now.
# criterion = "0.3"

[features]
default = ["canonical"]
canonical = ["rusqlite", "stacks_common/canonical"]
developer-mode = ["stacks_common/developer-mode"]
slog_json = ["stacks_common/slog_json"]
testing = ["canonical"]
devtools = []
rollback_value_check = []
disable-costs = []
