[package]
name = "stacks-node"
version = "0.1.0"
authors = ["Jude Nelson <jude@stacks.org>", "Aaron Blankstein <aaron@blockstack.com>", "Ludo Galabru <ludovic@blockstack.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.61"

[dependencies]
lazy_static = { workspace = true }
pico-args = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }
stacks = { workspace = true }
stx-genesis = { workspace = true }
base64 = { workspace = true }
backtrace = { workspace = true }
libc = { workspace = true }
slog = { workspace = true, features = ["max_level_trace"] }
clarity = { workspace = true }
stacks-common = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
libsigner = { workspace = true }
url = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
hashbrown = { workspace = true }
rusqlite = { workspace = true }
async-h1 = { workspace = true, optional = true }
async-std = { workspace = true, features = ["attributes"], optional = true }
http-types = { workspace = true, optional = true }
thiserror = { workspace = true }

[target.'cfg(not(any(target_os = "macos", target_os="windows", target_arch = "arm")))'.dependencies]
tikv-jemallocator = {workspace = true}

[dev-dependencies]
warp = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "json", "rustls", "rustls-tls"] }
clarity = { workspace = true, features = ["default", "testing"] }
stacks-common = { workspace = true, features = ["default", "testing"] }
stacks = { workspace = true, features = ["default", "testing"] }
stacks-signer = { workspace = true, features = ["testing"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
mutants = { workspace = true }
tiny_http = { workspace = true }
http-types = { workspace = true }
tempfile = { workspace = true }
mockito = { workspace = true }
serial_test = { workspace = true }

[[bin]]
name = "stacks-node"
path = "src/main.rs"

[[bin]]
name = "stacks-events"
path = "src/stacks_events.rs"

[features]
monitoring_prom = ["stacks/monitoring_prom", "libsigner/monitoring_prom", "stacks-signer/monitoring_prom", "async-h1", "async-std", "http-types"]
slog_json = ["stacks/slog_json", "stacks-common/slog_json", "clarity/slog_json"]
prod-genesis-chainstate = []
default = []
testing = []
